#!/usr/bin/env python3
"""
Generate a self-contained test kit for the app.

WHY THIS EXISTS. The real DFT workbook is publisher material and is gitignored,
so a public clone cannot exercise the three DFT tabs at all. This produces a
SYNTHETIC workbook with the same structure, plus CSVs that deliberately trip
every input guard, so the app's behaviour can be demonstrated end to end without
redistributing anyone's data.

NOTHING HERE IS CHEMISTRY. The adsorption energies are drawn from a documented
toy function of the site descriptors. They are plausible in range and ordering
so the plots look sensible, and they are NOT DFT results. Every file carries a
SYNTHETIC marker; the workbook carries one as a sheet you cannot miss.

Run:  python examples/test_kit/make_test_data.py
"""
from __future__ import annotations

import os
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))

# Same encoding the real workbook uses: (Group, Period, EN, unpaired d electrons)
ELEMENTS = {
    "Fe": (8, 4, 1.83, 4), "Co": (9, 4, 1.88, 3), "Ni": (10, 4, 1.91, 2),
    "Cu": (11, 4, 1.90, 0), "Mo": (6, 5, 2.16, 5),
}
SYMS = sorted(ELEMENTS)
N_SITES = 10

# Toy model: binding strengthens with the adsorption site's unpaired d count and
# weakens with its electronegativity, plus a small environment term. Chosen only
# to produce a learnable signal with a realistic spread.
COEF = {"CO": dict(base=-2.0, nd=-0.10, en=+0.45, env=-0.04, noise=0.05),
        "CHO": dict(base=-1.5, nd=-0.14, en=+0.60, env=-0.05, noise=0.09),
        "COOH": dict(base=-0.7, nd=-0.11, en=+0.50, env=-0.05, noise=0.07)}


def _columns():
    return [f"Site {k} {d}" for k in range(1, N_SITES + 1)
            for d in ("Group", "Period", "EN", "Nied")]


def _draw_configs(n, rng, exclude_site1=()):
    allowed = [s for s in SYMS if s not in exclude_site1]
    out = []
    for _ in range(n):
        cfg = list(rng.choice(SYMS, size=N_SITES))
        cfg[0] = str(rng.choice(allowed))
        out.append(cfg)
    return out


def _sheet(species: str, configs, rng):
    """One intermediate, over the configurations it was given."""
    c = COEF[species]
    rows, targets = [], []
    for cfg in configs:
        desc = [v for s in cfg for v in ELEMENTS[s]]
        nd1, en1 = ELEMENTS[cfg[0]][3], ELEMENTS[cfg[0]][2]
        env_nd = float(np.mean([ELEMENTS[s][3] for s in cfg[1:]]))
        y = (c["base"] + c["nd"] * nd1 + c["en"] * (en1 - 1.9)
             + c["env"] * env_nd + rng.normal(0, c["noise"]))
        rows.append(desc)
        targets.append(round(float(y), 4))
    df = pd.DataFrame(rows, columns=_columns())
    df.insert(0, "Labels", targets)          # duplicates the target, as in the real file
    df["Eads (eV)"] = targets
    return df


def main() -> int:
    rng = np.random.default_rng(20260811)

    marker = pd.DataFrame({
        "READ THIS": [
            "SYNTHETIC TEST DATA — NOT DFT RESULTS.",
            "Generated by examples/test_kit/make_test_data.py.",
            "Adsorption energies come from a toy function of the site "
            "descriptors, chosen so the app has a learnable signal.",
            "Use to exercise the interface. Never to draw a chemical conclusion.",
        ]})

    # A pool of configurations present in EVERY sheet, plus sheet-specific
    # extras. Without the shared pool the sheets never intersect, join_
    # intermediates returns nothing and the whole CHE/desorption path is
    # untestable — which is exactly what a first version of this script did.
    # Shared configurations avoid Cu at the adsorption site so they survive the
    # *CO sheet's exclusion.
    shared = _draw_configs(30, rng, exclude_site1=("Cu",))
    sheets = {
        # *CO deliberately excludes Cu at the adsorption site, mirroring the real
        # workbook, so the applicability guard has something real to catch.
        "CO":   _sheet("CO", shared + _draw_configs(130, rng, exclude_site1=("Cu",)), rng),
        "CHO":  _sheet("CHO", shared + _draw_configs(170, rng), rng),
        "COOH": _sheet("COOH", shared + _draw_configs(230, rng), rng),
    }
    path = os.path.join(HERE, "SYNTHETIC_HEA_workbook.xlsx")
    with pd.ExcelWriter(path, engine="openpyxl") as xw:
        marker.to_excel(xw, sheet_name="_SYNTHETIC_README", index=False)
        for name, df in sheets.items():
            df.to_excel(xw, sheet_name=name, index=False)
    print(f"wrote {path}")
    for k, v in sheets.items():
        print(f"  *{k:5} n={len(v):3}  Eads {v['Eads (eV)'].min():+.3f} .. "
              f"{v['Eads (eV)'].max():+.3f}  sd {v['Eads (eV)'].std():.3f}")

    # ---- CSV that trips every intake guard, one row per problem --------------
    csv = os.path.join(HERE, "measurements_edge_cases.csv")
    with open(csv, "w") as fh:
        fh.write("material,product,FE (%),cell voltage,current density\n")
        fh.write("clean-baseline,CO,90,3.0,200\n")          # nothing wrong
        fh.write("fe-as-percent,CO,92,3.1,250\n")           # 92 -> 0.92
        fh.write("voltage-in-mV,CO,88,3200,180\n")          # 3200 mV -> 3.2 V
        fh.write("very-slow-cell,CO,90,3.0,20\n")           # tiny j -> huge area/CAPEX
        fh.write("very-fast-cell,CO,90,3.0,900\n")          # large j -> small CAPEX
        fh.write("impossible-FE,CO,140,3.0,200\n")          # out of range -> error
    print(f"wrote {csv}")

    csv2 = os.path.join(HERE, "measurements_no_product_column.csv")
    with open(csv2, "w") as fh:
        fh.write("material,FE (%),cell voltage\n")
        fh.write("unknown-route-A,90,3.0\nunknown-route-B,85,3.3\n")
    print(f"wrote {csv2}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
